channels:
  - gurobi
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.11
  - pytorch=2.3.1
  - torchvision=0.18.1
  - torchaudio=2.3.1
  - pytorch-cuda=12.1
  - numpy
  - pandas
  - scikit-learn
  - scipy
  - pillow
  - matplotlib
  - tqdm
  - gurobi
  - pip
  - pip:
    - coloredlogs==15.0.1
    - flatbuffers==24.3.25
    - fsspec==2024.6.0
    - humanfriendly==10.0
    - git+https://github.com/Verified-Intelligence/onnx2pytorch@325959ed128200459a9634668149a722a6a74797#egg=onnx2pytorch
    - onnxconverter-common==1.14.0
    - onnxoptimizer==0.3.13
    - onnxruntime==1.18.0
    - onnxsim==0.4.36
    - protobuf==3.20.2
    - graphviz==0.20.3
    - skl2onnx==1.17.0 